services:
  # Admin Application
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
      target: development
    container_name: merchy-admin
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./admin/.env
    environment:
      - NODE_ENV=development
    networks:
      - ecommerce-network
    volumes:
      - ./admin:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "npm install --ignore-scripts && npx prisma generate && npx prisma db push && npm run dev -- --port 3000"

  # Store Application
  store:
    build:
      context: ./store
      dockerfile: Dockerfile
      target: development
    container_name: merchy-store
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://admin:3000/api/077c1cca-28ac-4cfe-a1af-be6894ef6dfe
    depends_on:
      - admin
    networks:
      - ecommerce-network
    volumes:
      - ./store:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "npm install && npm run dev -- --port 3001"

volumes:
  postgres_data:

networks:
  ecommerce-network:
    driver: bridge