version: '3.8'

services:
  admin:
    build:
      context: ./my-ecommerce-admin
      dockerfile: Dockerfile.dev
    container_name: ecommerce_admin_dev
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ecommerce
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./my-ecommerce-admin:/app
      - /app/node_modules
    command: sh -c "npm run dev"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/api/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - app_network

  customer:
    build:
      context: ./my-ecommerce-customer
      dockerfile: Dockerfile.dev
    container_name: ecommerce_customer_dev
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ecommerce
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - PORT=3001
      - NODE_ENV=development
    volumes:
      - ./my-ecommerce-customer:/app
      - /app/node_modules
    command: sh -c "npm run dev -- -p 3001"
    depends_on:
      postgres:
        condition: service_healthy
      admin:
        condition: service_healthy
    networks:
      - app_network

  postgres:
    image: postgres:13
    container_name: ecommerce_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
